import type { Database } from "./database.types";

type ImportRow = Database["public"]["Tables"]["imports"]["Row"];
type SuggestionRow = Database["public"]["Tables"]["pattern_suggestions"]["Row"];
type VaultNoteRow = Database["public"]["Tables"]["vault_notes"]["Row"];

const DEMO_USER = "demo-anon-user";
const t = (offsetMin: number) =>
  new Date(Date.now() - offsetMin * 60_000).toISOString();

export const DEMO_IMPORTS: ImportRow[] = [
  {
    id: "demo-imp-1",
    user_id: DEMO_USER,
    source: "github",
    label: "caua-ferreira/gestao-vendas-adriana",
    file_count: 38,
    status: "pronto",
    created_at: t(60 * 24 * 2),
    finished_at: t(60 * 24 * 2 - 3),
    provider_used: "brainfrost",
    raw_text: null,
    error: null,
  },
  {
    id: "demo-imp-2",
    user_id: DEMO_USER,
    source: "zip",
    label: "folha-diaria.zip",
    file_count: 21,
    status: "pronto",
    created_at: t(60 * 6),
    finished_at: t(60 * 6 - 2),
    provider_used: "webllm",
    raw_text: null,
    error: null,
  },
  {
    id: "demo-imp-3",
    user_id: DEMO_USER,
    source: "text",
    label: "CONTEXTO.md colado",
    file_count: 1,
    status: "pronto",
    created_at: t(30),
    finished_at: t(28),
    provider_used: "brainfrost",
    raw_text: null,
    error: null,
  },
];

export const DEMO_SUGGESTIONS: SuggestionRow[] = [
  {
    id: "demo-sug-1",
    user_id: DEMO_USER,
    import_id: "demo-imp-3",
    title: "RLS por auth.uid() em toda tabela multiusuário",
    body: "Toda tabela com dado por pessoa aplica policy `USING (auth.uid() = user_id)` e trigger de dono no insert. Único por (user_id, chave), nunca global.",
    category: "padroes_arquitetura",
    evidence: "supabase/migrations/0001_init.sql:12",
    status: "pending",
    accepted_note_id: null,
    created_at: t(28),
  },
  {
    id: "demo-sug-2",
    user_id: DEMO_USER,
    import_id: "demo-imp-3",
    title: "Fallback de env em lib/supabase/config.ts",
    body: "Deploy pelo conector da Vercel não grava env. URL e anon key vão como fallback de `process.env` no arquivo `lib/supabase/config.ts`.",
    category: "padrao_webapp",
    evidence: "lib/supabase/config.ts:3",
    status: "pending",
    accepted_note_id: null,
    created_at: t(27),
  },
  {
    id: "demo-sug-3",
    user_id: DEMO_USER,
    import_id: "demo-imp-2",
    title: "Debounce de 700ms no auto-save",
    body: "Patch acumulado em ref e gravado com debounce de 700ms. Também dispara ao trocar de dia ou esconder a aba.",
    category: "padroes_codigo",
    evidence: "components/DailyPlanner.tsx:184",
    status: "pending",
    accepted_note_id: null,
    created_at: t(60 * 6 - 1),
  },
  {
    id: "demo-sug-4",
    user_id: DEMO_USER,
    import_id: "demo-imp-1",
    title: "Alvo de toque grande e fonte legível",
    body: "Mobile-first com alvo de toque >= 44px, fonte base 16px, nada de hover como único caminho para uma ação.",
    category: "padrao_webapp",
    evidence: "app/globals.css:8",
    status: "pending",
    accepted_note_id: null,
    created_at: t(60 * 24 * 2 - 2),
  },
  {
    id: "demo-sug-5",
    user_id: DEMO_USER,
    import_id: "demo-imp-1",
    title: "Conventional Commits sem coautoria",
    body: "Formato tipo(scope): descrição. Scope opcional. Coautoria não é usada — quem colabora entra na descrição do PR, não no commit.",
    category: "padroes_codigo",
    evidence: ".github/CONTRIBUTING.md:8",
    status: "accepted",
    accepted_note_id: "demo-note-1",
    created_at: t(60 * 24 * 2 - 2),
  },
  {
    id: "demo-sug-6",
    user_id: DEMO_USER,
    import_id: "demo-imp-1",
    title: "GMUD antes de mudança em produção",
    body: "Alteração em Control-M, Airflow ou Jenkins exige GMUD. Antes de propor mudança, listar o que quebra se o passo anterior atrasar.",
    category: "contexto_trabalho",
    evidence: "docs/deploy.md:44",
    status: "accepted",
    accepted_note_id: "demo-note-2",
    created_at: t(60 * 24 * 2 - 1),
  },
];

export const DEMO_VAULT_NOTES: VaultNoteRow[] = [
  {
    id: "demo-note-1",
    user_id: DEMO_USER,
    slug: "conventional-commits-sem-coautoria",
    title: "Conventional Commits sem coautoria",
    body: "Formato tipo(scope): descrição. Scope opcional. Coautoria não é usada — quem colabora entra na descrição do PR, não no commit.",
    category: "padroes_codigo",
    layer: "growth",
    tags: ["commits", "processo"],
    created_at: t(60 * 24 * 2 - 2),
    updated_at: t(60 * 24 * 2 - 2),
  },
  {
    id: "demo-note-2",
    user_id: DEMO_USER,
    slug: "gmud-antes-de-producao",
    title: "GMUD antes de mudança em produção",
    body: "Alteração em Control-M, Airflow ou Jenkins exige GMUD. Antes de propor mudança, listar o que quebra se o passo anterior atrasar.",
    category: "contexto_trabalho",
    layer: "core",
    tags: ["produção", "processo"],
    created_at: t(60 * 24 * 2 - 1),
    updated_at: t(60 * 24 * 2 - 1),
  },
  {
    id: "demo-note-3",
    user_id: DEMO_USER,
    slug: "medalhao-bronze-silver-gold",
    title: "Arquitetura medalhão: Bronze/Silver/Gold",
    body: "Bronze é dado cru sem cast. Silver normaliza tipo, chave e dedup. Gold só materializa o que o Power BI consome — nada de regra nova na Gold que não esteja documentada.",
    category: "padroes_arquitetura",
    layer: "core",
    tags: ["snowflake", "modelagem"],
    created_at: t(60 * 24 * 3),
    updated_at: t(60 * 24 * 3),
  },
  {
    id: "demo-note-4",
    user_id: DEMO_USER,
    slug: "supabase-fallback-env",
    title: "Fallback de env do Supabase",
    body: "Deploy pelo conector da Vercel não grava env. URL e anon key vão como fallback de `process.env` em `lib/supabase/config.ts`.",
    category: "padrao_webapp",
    layer: "growth",
    tags: ["supabase", "vercel"],
    created_at: t(60 * 24 * 1),
    updated_at: t(60 * 24 * 1),
  },
];
